create table public.agentreports (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  user_details json null,
  agent_id bigint null,
  payment_mode text null,
  transaction_id text null,
  paid_amount integer null,
  pdf_url text null,
  tokens_used integer not null,
  plan_id bigint null,
  branch_id bigint not null,
  constraint agentreports_pkey primary key (id),
  constraint agentreports_agent_id_fkey foreign KEY (agent_id) references agentdata (id) on update CASCADE on delete CASCADE,
  constraint agentreports_branch_id_fkey foreign KEY (branch_id) references branch (id),
  constraint agentreports_plan_id_fkey foreign KEY (plan_id) references pricing_plans (id)
) TABLESPACE pg_default;