create table public.agentdata (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  email text not null,
  tokens_total integer not null default 0,
  tokens_used integer null default 0,
  name text null,
  phone text null,
  revenue integer null default 0,
  agent_uuid uuid null,
  constraint agentdata_pkey primary key (id),
  constraint agentdata_email_key unique (email),
  constraint agentdata_agent_uuid_fkey foreign KEY (agent_uuid) references auth.users (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;