create table public.branch (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  name text not null,
  agent_id uuid null,
  total_reports integer null default 0,
  total_revenue integer null default 0,
  type_1_reports integer null default 0,
  type_2_reports integer null default 0,
  type_3_reports integer null default 0,
  constraint branch_pkey primary key (id)
) TABLESPACE pg_default;