-- ==========================================
-- UREKHA DATABASE COMPLETE SETUP SCRIPT
-- ==========================================
-- This script safely drops and recreates all tables in the correct 
-- dependency order, and applies the UNIVERSAL PUBLIC READ policies.

-- 1. DROP EXISTING TABLES (Reverse Dependency Order)
DROP TABLE IF EXISTS public.token_transactions CASCADE;
DROP TABLE IF EXISTS public.agentreports CASCADE;
DROP TABLE IF EXISTS public.branch CASCADE;
DROP TABLE IF EXISTS public.agentdata CASCADE;
DROP TABLE IF EXISTS public.userdata CASCADE;
DROP TABLE IF EXISTS public.roles CASCADE;
DROP TABLE IF EXISTS public.pricing_plans CASCADE;

-- 2. CREATE TABLES

-- Table: roles
create table public.roles (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  role text null,
  email text not null,
  constraint roles_pkey primary key (id)
) TABLESPACE pg_default;

-- Table: pricing_plans
create table public.pricing_plans (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  target_audience text not null default 'user',
  name text not null,
  description text null,
  price numeric not null default 0, 
  currency text not null default 'INR', 
  billing_cycle text null default 'one-time',
  tokens_included integer not null default 0,
  token_cost integer not null default 0,
  features jsonb not null default '[]'::jsonb,
  is_popular boolean not null default false,
  is_active boolean not null default true,
  display_order integer not null default 0,
  stripe_price_id text null,
  constraint pricing_plans_pkey primary key (id)
) TABLESPACE pg_default;

-- Table: userdata
create table public.userdata (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  email text not null,
  name text null,
  date_of_birth date null,
  time_of_birth text null,
  state text null,
  city text null,
  longitude real null,
  latitude real null,
  country text null default ''::text,
  gender text null,
  profile_complete boolean not null default false,
  constraint userdata_pkey primary key (id),
  constraint userdata_email_key unique (email)
) TABLESPACE pg_default;

-- Table: agentdata
create table public.agentdata (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  email text not null,
  agent_id uuid not null default gen_random_uuid(),
  tokens_total integer not null default 0,
  tokens_used integer null default 0,
  name text null,
  phone text null,
  revenue integer null default 0,
  constraint agentdata_pkey primary key (id),
  constraint agentdata_email_key unique (email)
) TABLESPACE pg_default;

-- Table: branch
create table public.branch (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  name text not null,
  agent_id uuid null,
  total_reports integer null default 0,
  total_revenue integer null default 0,
  type_1_reports integer null default 0,
  type_2_reports integer null default 0,
  type_3_reports integer null default 0,
  constraint branch_pkey primary key (id)
) TABLESPACE pg_default;

-- Table: agentreports
create table public.agentreports (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  user_details json null,
  agent_id bigint null,
  plan text null,
  payment_mode text null,
  transaction_id text null,
  paid_amount integer null,
  pdf_url text null,
  constraint agentreports_pkey primary key (id),
  constraint agentreports_agent_id_fkey foreign key (agent_id) references agentdata (id) on update cascade on delete cascade
) TABLESPACE pg_default;

-- Table: token_transactions
create table public.token_transactions (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  agent_id bigint not null,
  amount integer not null,
  status text not null default 'pending',
  remarks text null,
  approved_by text null,
  approved_at timestamp with time zone null,
  constraint token_transactions_pkey primary key (id),
  constraint token_transactions_agent_id_fkey foreign key (agent_id) references agentdata (id) on delete cascade
) TABLESPACE pg_default;


-- ==========================================
-- 3. APPLY ROW LEVEL SECURITY (RLS) & PUBLIC PERMISSIONS
-- ==========================================

ALTER TABLE agentdata ENABLE ROW LEVEL SECURITY;
ALTER TABLE userdata ENABLE ROW LEVEL SECURITY;
ALTER TABLE agentreports ENABLE ROW LEVEL SECURITY;
ALTER TABLE token_transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE pricing_plans ENABLE ROW LEVEL SECURITY;
ALTER TABLE branch ENABLE ROW LEVEL SECURITY;

-- 3A. Public SELECT Policies (Anyone can read, avoids dashboard blank data issues)
CREATE POLICY "Public can view all agentdata" ON agentdata FOR SELECT USING (true);
CREATE POLICY "Public can view all userdata" ON userdata FOR SELECT USING (true);
CREATE POLICY "Public can view all agentreports" ON agentreports FOR SELECT USING (true);
CREATE POLICY "Public can view all token_transactions" ON token_transactions FOR SELECT USING (true);
CREATE POLICY "Public can view all roles" ON roles FOR SELECT USING (true);
CREATE POLICY "Public can view all pricing_plans" ON pricing_plans FOR SELECT USING (true);
CREATE POLICY "Public can view all branch" ON branch FOR SELECT USING (true);


-- 3B. Public INSERT Policies (Since Authentication ensures roles exist during signup)
-- Note: A completely open INSERT policy is dangerous in production, but we will allow authenticated users or service roles to insert.
CREATE POLICY "Enable insert for authenticated users only" ON userdata FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Enable insert for authenticated users only" ON agentdata FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Enable insert for authenticated users only" ON roles FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Enable insert for authenticated users only" ON token_transactions FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Enable insert for authenticated users only" ON agentreports FOR INSERT TO authenticated WITH CHECK (true);

-- 3C. Update Policies
-- Agentdata needs to be updated by users themselves (during signup/profile completion) OR admins (when approving tokens)
CREATE POLICY "Enable update for all authenticated users" ON agentdata FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Enable update for all authenticated users" ON userdata FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Enable update for all authenticated users" ON token_transactions FOR UPDATE TO authenticated USING (true) WITH CHECK (true);


-- ==========================================
-- 4. INSERT DEFAULT DATA (Optional but recommended)
-- ==========================================

-- Insert the admin role so you can access the admin panel immediately upon signing up
-- Make sure to change 'roshan.stats@gmail.com' to your actual login email!
INSERT INTO public.roles (role, email) VALUES
('admin', 'roshan.stats@gmail.com'),
('admin', 'admin@urekha.com')
ON CONFLICT DO NOTHING;

-- Insert default Pricing Plans
INSERT INTO public.pricing_plans (target_audience, name, description, price, tokens_included, token_cost, is_popular, is_active, display_order) VALUES
('agent', 'Basic Report Gen', 'Deducts 2000 tokens per report generate', 0, 0, 2000, false, true, 1),
('agent', 'Standard Report Gen', 'Deducts 3000 tokens per report generate', 0, 0, 3000, true, true, 2)
ON CONFLICT DO NOTHING;
