-- ==========================================
-- TABLE: generated_kundlis
-- Purpose: Store unique kundli birth detail fingerprints for deduplication.
-- Deduplication: Global across all agents.
-- Coordinates rounded to 2 decimal places (~1km precision).
-- ==========================================

CREATE TABLE public.generated_kundlis (
  id bigint generated by default as identity not null,
  created_at timestamptz not null default now(),
  
  -- Birth Detail Fingerprint (deduplication key)
  dob date not null,
  tob text not null,                   -- "HH:mm" format
  latitude numeric(7,2) not null,      -- Auto-rounds to 2 decimal places on insert
  longitude numeric(8,2) not null,     -- Auto-rounds to 2 decimal places on insert
  
  -- Metadata (NOT part of dedup key)
  name text null,
  gender text null,
  location_name text null,
  
  -- Who generated it first
  agent_id bigint null,
  
  -- Plan & cost tracking
  plan_id bigint null,
  tokens_deducted integer not null default 0,
  
  -- Constraints
  constraint generated_kundlis_pkey primary key (id),
  constraint generated_kundlis_agent_fkey foreign key (agent_id) references agentdata(id) on delete set null,
  constraint generated_kundlis_plan_fkey foreign key (plan_id) references pricing_plans(id) on delete set null,
  constraint generated_kundlis_unique_birth unique (dob, tob, latitude, longitude)
) TABLESPACE pg_default;

-- Row Level Security
ALTER TABLE generated_kundlis ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public can view all generated_kundlis" ON generated_kundlis FOR SELECT USING (true);
CREATE POLICY "Authenticated can insert generated_kundlis" ON generated_kundlis FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Authenticated can update generated_kundlis" ON generated_kundlis FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
