create table public.pricing_plans (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  
  -- Target Audience ('user' or 'agent')
  target_audience text not null default 'user',
  
  -- Core Details
  name text not null, -- e.g. 'Starter' (user) or 'Basic Report' (agent)
  description text null, -- Short description shown on card
  
  -- Pricing (for Users purchasing plans/tokens, or Agents buying bulk tokens if needed)
  price numeric not null default 0, 
  currency text not null default 'INR', 
  billing_cycle text null default 'one-time', -- e.g. 'monthly', 'yearly', 'one-time', null for agents
  
  -- Token Economy
  tokens_included integer not null default 0, -- Tokens given to a USER when they buy this plan
  token_cost integer not null default 0, -- Tokens deducted from an AGENT when they generate a report with this plan
  
  -- UI & Marketing Display
  features jsonb not null default '[]'::jsonb, -- Array of features: ["Feature 1", "Feature 2"]
  is_popular boolean not null default false, -- Highlights the recommended plan on the UI
  is_active boolean not null default true, -- Toggle visibility on frontend without deleting
  display_order integer not null default 0, -- Determine order of appearance (0, 1, 2...)
  
  -- E-commerce Integration
  stripe_price_id text null, -- If you integrate Razorpay / Stripe later
  
  constraint pricing_plans_pkey primary key (id)
) TABLESPACE pg_default;
