 -- Table: prompts
-- Stores the AI prompt templates and their respective astrological data requirements.
create table public.prompts (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  name text not null, -- e.g. 'Health Prediction'
  slug text not null, -- e.g. 'health-prediction'
  prompt_template text not null, -- The actual AI prompt instructions
  input_data_codes jsonb not null default '[]'::jsonb, -- e.g. ["CHART_D1", "HORO_PL_DET"]
  word_count_target integer not null default 500,
  is_active boolean not null default true,
  constraint prompts_pkey primary key (id),
  constraint prompts_slug_key unique (slug)
) TABLESPACE pg_default;

-- Table: pricing_plan_prompts
-- Junction table to link pricing plans to multiple prediction prompts.
create table public.pricing_plan_prompts (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  plan_id bigint not null references public.pricing_plans(id) on delete cascade,
  prompt_id bigint not null references public.prompts(id) on delete cascade,
  display_order integer not null default 0,
  constraint pricing_plan_prompts_pkey primary key (id)
) TABLESPACE pg_default;

-- Enable RLS
ALTER TABLE public.prompts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pricing_plan_prompts ENABLE ROW LEVEL SECURITY;

-- Public read policies
CREATE POLICY "Public can view all prompts" ON public.prompts FOR SELECT USING (true);
CREATE POLICY "Public can view all plan prompts" ON public.pricing_plan_prompts FOR SELECT USING (true);
