create table public.roles (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  role text null,
  email text not null,
  user_id uuid null,
  constraint roles_pkey primary key (id),
  constraint roles_user_id_fkey foreign KEY (user_id) references auth.users (id) on update CASCADE on delete RESTRICT
) TABLESPACE pg_default;