create table public.token_transactions (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  agent_id bigint not null,
  amount integer not null,
  status text not null default 'pending',
  remarks text null,
  approved_by text null,
  approved_at timestamp with time zone null,
  
  constraint token_transactions_pkey primary key (id),
  constraint token_transactions_agent_id_fkey foreign key (agent_id) references agentdata (id) on delete cascade
) TABLESPACE pg_default;
