create table public.userdata (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  email text not null,
  name text null,
  date_of_birth date null,
  time_of_birth text null,
  state text null,
  city text null,
  longitude real null,
  latitude real null,
  country text null default ''::text,
  gender text null,
  profile_complete boolean not null default false,
  constraint userdata_pkey primary key (id),
  constraint userdata_email_key unique (email)
) TABLESPACE pg_default;