import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Terms of Service | Urekha",
    description: "Legal terms and conditions for using Urekha.",
};

export default function TermsPage() {
    return (
        <main className="pt-32 pb-24 px-6 md:px-12 max-w-4xl mx-auto min-h-screen">
            <h1 className="text-4xl md:text-5xl font-serif text-brand-gold mb-8">Terms of Service</h1>
            <p className="text-muted-foreground mb-12">Last Updated: January 2026</p>

            <div className="space-y-8 text-foreground/80 leading-relaxed">
                <section>
                    <h2 className="text-2xl font-serif text-white mb-4">1. Acceptance of Terms</h2>
                    <p>
                        By accessing or using Urekha, you agree to be bound by these Terms. If you disagree with any part of the terms, you must not use our services.
                    </p>
                </section>

                <div className="p-6 border border-brand-gold/30 bg-brand-gold/5 rounded-xl my-8">
                    <h2 className="text-xl font-serif text-brand-gold mb-2">CRITICAL DISCLAIMER: AI & PREDICTIONS</h2>
                    <p className="text-sm">
                        <strong>Urekha is an AI-powered data processing tool.</strong> The reports, insights, and predictions provided are based on algorithmic interpretation of astrological principles.
                        They are for <strong>entertainment, research, and self-reflection purposes only</strong>.
                        Urekha does NOT provide medical, legal, financial, or psychological advice.
                        You acknowledge that any decisions you make based on our reports are your sole responsibility.
                        <strong>We strictly disclaim any liability for actions taken on the basis of our AI-generated content.</strong>
                    </p>
                </div>

                <section>
                    <h2 className="text-2xl font-serif text-white mb-4">2. Nature of Service</h2>
                    <p>
                        Our reports are generated by software. While we strive for astronomical accuracy in calculation, the interpretive text is synthetic.
                        We do not guarantee that the events predicted will occur. Astrology is an interpretive framework, not an exact science.
                    </p>
                </section>

                <section>
                    <h2 className="text-2xl font-serif text-white mb-4">3. Refunds & Cancellations</h2>
                    <p>
                        <strong>Digital Reports:</strong> Due to the immediate nature of digital content generation, mere dissatisfaction with the "prediction" or "reading" is not grounds for a refund. Refunds are only processed for technical failures (e.g., blank report, generation error).<br /><br />
                        <strong>Physical Goods:</strong> Damaged physical reports will be replaced at no cost.
                    </p>
                </section>

                <section>
                    <h2 className="text-2xl font-serif text-white mb-4">4. Intellectual Property</h2>
                    <p>
                        The generated report layout, design, and specific AI model outputs are the property of Urekha. You are granted a personal, non-commercial license to use your specific report.
                    </p>
                </section>

                <section>
                    <h2 className="text-2xl font-serif text-white mb-4">5. Limitation of Liability</h2>
                    <p>
                        To the maximum extent permitted by law, Urekha shall not be liable for any indirect, incidental, special, consequential, or punitive damages resulting from your use of the service.
                    </p>
                </section>
            </div>
        </main>
    );
}
