"use client";

import { motion, AnimatePresence } from "framer-motion";
import { ChevronDown } from "lucide-react";
import { useState } from "react";
import PremiumHero from "@/components/ui/PremiumHero";

const FAQ_ITEMS = [
    { q: "Is this generated by a real astrologer?", a: "No. It is generated by an advanced AI engine trained on the logic of thousands of expert astrologers. This ensures consistent, mathematically precise analysis without human fatigue or bias." },
    { q: "How accurate is the birth time requirement?", a: "Very. We recommend accuracy within +/- 5 minutes. If your birth time is unknown, we cannot generate a Divisional Chart analysis reliably." },
    { q: "Can I get a refund if I don't like my prediction?", a: "As stated in our Terms, we do not refund based on the content of the reading. Refunds are only for technical failures." },
    { q: "Do you ship internationally?", a: "Yes, we ship hardcover reports to over 150 countries via DHL/FedEx." },
    { q: "What Ayanamsa do you use?", a: "By default, we use Lahiri (Chitrapaksha) Ayanamsa. Advanced users can select Raman or Krishnamurti in the settings." },
    { q: "Is my data private?", a: "Absolutely. We encrypt all birth data and automatically delete it from our servers 30 days after your report is generated." }
];

export default function FAQPage() {
    const [openIndex, setOpenIndex] = useState<number | null>(0);

    return (
        <main className="min-h-screen bg-background relative overflow-hidden">
            <PremiumHero
                badge="Knowledge Base"
                title="Frequently Asked Questions"
                description="Everything you need to know about our methodology, shipping, and privacy policies."
            />

            <div className="container mx-auto px-6 pb-24 max-w-3xl">
                <div className="space-y-4">
                    {FAQ_ITEMS.map((item, i) => (
                        <motion.div
                            key={i}
                            initial={{ opacity: 0, y: 20 }}
                            whileInView={{ opacity: 1, y: 0 }}
                            transition={{ delay: i * 0.1 }}
                            className="glass-card rounded-2xl border border-white/10 overflow-hidden hover:border-brand-gold/30 transition-all duration-300"
                        >
                            <button
                                onClick={() => setOpenIndex(openIndex === i ? null : i)}
                                className="w-full p-6 text-left flex items-center justify-between gap-4 group cursor-pointer"
                            >
                                <h3 className="text-lg md:text-xl font-bold text-foreground group-hover:text-brand-gold transition-colors">
                                    {item.q}
                                </h3>
                                <ChevronDown
                                    className={`w-5 h-5 text-brand-gold shrink-0 transition-transform duration-300 ${openIndex === i ? 'rotate-180' : ''}`}
                                />
                            </button>

                            <AnimatePresence>
                                {openIndex === i && (
                                    <motion.div
                                        initial={{ height: 0, opacity: 0 }}
                                        animate={{ height: "auto", opacity: 1 }}
                                        exit={{ height: 0, opacity: 0 }}
                                        transition={{ duration: 0.3 }}
                                        className="overflow-hidden"
                                    >
                                        <div className="px-6 pb-6 pt-0">
                                            <p className="text-muted-foreground leading-relaxed border-t border-border pt-4">
                                                {item.a}
                                            </p>
                                        </div>
                                    </motion.div>
                                )}
                            </AnimatePresence>
                        </motion.div>
                    ))}
                </div>
            </div>
        </main>
    );
}
